.\" Manpage for carchey.
.\" Contact dongcarl@fastmail.com to correct errors or typos.
.TH CARCHEY 1 "05 Jan 2016" "Prolific" "carchey"
.SH NAME
carchey \- a system information tool for OS X written in C.
.SH SYNOPSIS
carchey [-c]
.SH DESCRIPTION
carchey prints, along with an Apple logo, the current effective user's user name, the name of the current host, the OS X product version of the current system, the name of the current operating system, the uptime of the system, the current shell, the current terminal type, the number of packages installed by brew(1), the CPU of the current system, the current system's memory capacity, the percent free of "/", and the percentage of battery left.
.SH OPTIONS
.IP -c
disables coloring of the Apple logo
.SH AUTHOR
Carl Dong (dongcarl@fastmail.com)
